version: '2'

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.template
      - ./:/var/www/testik
    ports:
      - "${EXTERNAL_PORT}:80"
    depends_on:
      - app
    environment:
      - PORT=${PORT}
    command: /bin/bash -c "envsubst '$${PORT}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=practice_db
    ports:
      - 54327:5432
    volumes:
      - postgresql:/var/lib/postgresql

  app:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/var/www/testik:delegated
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; sh start.sh; php-fpm -F -R'

volumes:
  postgresql:

networks:
  default:
